### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by lukauskas** [bayespy/bayespy#26] opened 2015-10-30 15:05 UTC
[Bernoulli mixture model tutorial](http://www.bayespy.org/examples/bmm.html) fails on Python 2.7.10 due to syntax error in "bayespy/utils/misc.py". 

Namely, [line 49](https://github.com/bayespy/bayespy/blob/master/bayespy/utils/misc.py#L49):
```
def parse_command_line_arguments(mandatory_args, *optional_args_list, argv=None):
```

Perhaps you meant:
```
def parse_command_line_arguments(mandatory_args, argv=None, *optional_args_list):
```

?

**Comment by lukauskas** [comment] 2015-10-30 16:00
Okay, I did some digging, and my proposed option to put `argv=None` would not be correct.
One would have to implement something like:

```
def parse_command_line_arguments(mandatory_args, *optional_args_list, **kwargs):
    argv = kwargs.get('argv', None)
```

I implemented this in my own fork of the code, but now I notice, this has not been the only place positional arguments have been used like that in the code. For instance, it is also used [here](https://github.com/bayespy/bayespy/blob/master/bayespy/utils/misc.py#L693), and in a couple other places in the package.

From this, I guess Python 2 support is not on the roadmap for the package, is it?

**Comment by jluttine** [comment] 2015-10-31 11:50
Yep, Python 2 isn't supported unfortunately. BayesPy will raise an error in the future if one tries to install it with Python 2: https://github.com/bayespy/bayespy/commit/3fbb8d5d31654319984f35a6d1b1529df9e37ffa . It will be in the next release probably.

I chose not to support Python 2 because I liked some features in Python 3, and wanted to avoid doing the transition in the near future and needing to support two versions of Pythons. This same "bug" has been reported so many times that maybe it was a wrong choice. Anyway, I hope the installation error will at least avoid some confusion because the problem is then clearly stated.

**Closed by jluttine** 2015-10-31 11:50 UTC

**Comment by lukauskas** [comment] 2015-11-01 20:32
It all makes sense. In this case, I think preventing installation to complete for Python 2 is indeed the way to go.
